/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokemonZaDonutIndexRouteImport } from './routes/pokemon-za-donut/index'
import { Route as PokemonZaDonutDemoTableRouteImport } from './routes/pokemon-za-donut/demo/table'

const PokemonZaDonutIndexRoute = PokemonZaDonutIndexRouteImport.update({
  id: '/pokemon-za-donut/',
  path: '/pokemon-za-donut/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonZaDonutDemoTableRoute = PokemonZaDonutDemoTableRouteImport.update({
  id: '/pokemon-za-donut/demo/table',
  path: '/pokemon-za-donut/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/pokemon-za-donut': typeof PokemonZaDonutIndexRoute
  '/pokemon-za-donut/demo/table': typeof PokemonZaDonutDemoTableRoute
}
export interface FileRoutesByTo {
  '/pokemon-za-donut': typeof PokemonZaDonutIndexRoute
  '/pokemon-za-donut/demo/table': typeof PokemonZaDonutDemoTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/pokemon-za-donut/': typeof PokemonZaDonutIndexRoute
  '/pokemon-za-donut/demo/table': typeof PokemonZaDonutDemoTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/pokemon-za-donut' | '/pokemon-za-donut/demo/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/pokemon-za-donut' | '/pokemon-za-donut/demo/table'
  id: '__root__' | '/pokemon-za-donut/' | '/pokemon-za-donut/demo/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PokemonZaDonutIndexRoute: typeof PokemonZaDonutIndexRoute
  PokemonZaDonutDemoTableRoute: typeof PokemonZaDonutDemoTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokemon-za-donut/': {
      id: '/pokemon-za-donut/'
      path: '/pokemon-za-donut'
      fullPath: '/pokemon-za-donut'
      preLoaderRoute: typeof PokemonZaDonutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon-za-donut/demo/table': {
      id: '/pokemon-za-donut/demo/table'
      path: '/pokemon-za-donut/demo/table'
      fullPath: '/pokemon-za-donut/demo/table'
      preLoaderRoute: typeof PokemonZaDonutDemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PokemonZaDonutIndexRoute: PokemonZaDonutIndexRoute,
  PokemonZaDonutDemoTableRoute: PokemonZaDonutDemoTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
